# Generated by Django 4.2.13 on 2024-11-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
