# Generated by Django 4.2.16 on 2024-11-16 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.SmallIntegerField(default=0)),
                ('p2_score', models.SmallIntegerField(default=0)),
                ('p1_exchange', models.SmallIntegerField(default=0)),
                ('p2_exchange', models.SmallIntegerField(default=0)),
                ('winning_score', models.SmallIntegerField(default=5)),
                ('type', models.CharField(choices=[('PONG', 'Pong'), ('SLAP', 'Slap')], default='PONG', max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('FINISH', 'Finished')], default='PEND', max_length=16)),
                ('round', models.SmallIntegerField(null=True)),
                ('p1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('ACCEPT', 'Accepted'), ('CLOSED', 'Closed')], default='PEND', max_length=16)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
    ]
