# Generated by Django 4.2.16 on 2024-11-24 07:09

from django.db import migrations, models
import shared_models.models.tournament


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('ACCEPT', 'Accepted'), ('DENIED', 'Denied')], default='PEND', max_length=16)),
                ('game', models.CharField(choices=[('PONG', 'Pong'), ('SLAP', 'Slap')], default='PONG', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.SmallIntegerField(default=0)),
                ('p2_score', models.SmallIntegerField(default=0)),
                ('p1_exchange', models.SmallIntegerField(default=0)),
                ('p2_exchange', models.SmallIntegerField(default=0)),
                ('winning_score', models.SmallIntegerField(default=5)),
                ('type', models.CharField(choices=[('PONG', 'Pong'), ('SLAP', 'Slap')], default='PONG', max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('FINISH', 'Finished')], default='PEND', max_length=16)),
                ('round', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared_models.models.tournament.PathAndRename('tournaments/'))),
                ('capacity', models.SmallIntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('win_score', models.SmallIntegerField(default=5)),
                ('type', models.CharField(choices=[('PUB', 'Public'), ('PRV', 'Private')], default='PUB', max_length=16)),
                ('private_key', models.CharField(max_length=128, null=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('LOCK', 'Locked'), ('ONGO', 'Ongoing'), ('FINISH', 'Finished')], default='PEND', max_length=16)),
                ('current_round', models.SmallIntegerField(default=1)),
                ('rounds', models.SmallIntegerField(default=2)),
                ('participants_count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
