# Generated by Django 4.2.16 on 2024-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_rename_blocked_friendship_user1_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('PONG', 'Pong'), ('SLAP', 'Slap')], default='PONG', max_length=8),
        ),
    ]
