# Generated by Django 4.2.16 on 2024-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
